version: "3.9"

services:
  php:
    build:
      context: ./docker/php
    volumes:
      - ./app:/var/www/html
    networks:
      - atexo

  nginx:
    build:
      context: ./docker/nginx
    volumes:
      - ./app:/var/www/html
      - ./docker/nginx/templates/default.conf.template:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"
      - "443:443"
    networks:
      - atexo

networks:
  atexo:
