version: "3.9"

services:

  front:
    build:
      context: ./docker/angular
      target: builder
    volumes:
      - ./app/front:/project
      - /project/node_modules
    ports:
      - "4200:4200"
    networks:
      - atexo

  php:
    build:
      context: ./docker/php
    volumes:
      - ./app:/var/www/html
    networks:
      - atexo

  nginx:
    build:
      context: ./docker/nginx
    volumes:
      - ./app:/var/www/html
      - ./docker/nginx/templates/default.conf.template:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"
      - "443:443"
    networks:
      - atexo

networks:
  atexo:
